runtime: nodejs18
env: standard

instance_class: F2

handlers:
  - url: /.*
    script: auto

env_variables:
  DB_PATH: /mnt/smartdb

beta_settings:
  cloud_sql_instances: ""

volumes:
  - name: smartdb
    gcs_bucket:
      bucket_name: smartuniversity-db

manual_scaling:
  instances: 1

volume_mounts:
  - name: smartdb
    mount_path: /mnt/smartdb
